import Counter from '@/components/Counter';

export const metadata = {
  title: "Home Page",
  description: "Generated by Home Page Component",
};

export default function page() {
  return (
    <>
      <h1 className='text-3xl text-center py-10 font-bold underline'>
        Home Page
      </h1>
      <Counter />
      <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Saepe sapiente repudiandae porro itaque hic necessitatibus explicabo maiores temporibus unde iure. Impedit eos unde error sequi at. Assumenda eum laudantium quos?
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Saepe sapiente repudiandae porro itaque hic necessitatibus explicabo maiores temporibus unde iure. Impedit eos unde error sequi at. Assumenda eum laudantium quos? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Saepe sapiente repudiandae porro itaque hic necessitatibus explicabo maiores temporibus unde iure. Impedit eos unde error sequi at. Assumenda eum laudantium quos? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Saepe sapiente repudiandae porro itaque hic necessitatibus explicabo maiores temporibus unde iure. Impedit eos unde error sequi at. Assumenda eum laudantium quos?
      </p>
    </>
  )
}

