import React from 'react'

export const metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

export default function Aboutpage() {
    return (
        <div>
            <h1 className='text-3xl text-center py-10 font-bold underline'>
                About Page
            </h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam quod error corrupti facilis incidunt modi mollitia voluptatibus quas aperiam odit alias dolorem rem veniam, itaque, cum molestiae quia deleniti praesentium.
                Iure nihil ipsam fuga, soluta incidunt doloribus dolorum accusantium adipisci quod. Rerum neque sapiente temporibus architecto aperiam, iusto magni quibusdam non, ducimus officiis culpa eum inventore aliquam beatae quas doloribus.
                Facilis neque odit praesentium nulla? Eos asperiores est dolorum quisquam blanditiis sequi veniam, quasi iste labore quo incidunt a deleniti ipsum laborum sunt, dicta perferendis, consectetur libero? Fuga, saepe minus?
                Aliquid facilis nesciunt eos rerum. Nam asperiores molestias deleniti incidunt corporis quidem quam dolorem ea nobis expedita qui ab excepturi nisi odit aliquam praesentium, harum numquam sapiente iste nemo itaque.
                Deserunt, nobis ex. Quam modi eveniet eaque perspiciatis beatae, quasi soluta ex, voluptas quis distinctio labore hic minus natus asperiores, ab tempora error molestiae vel omnis blanditiis iure! Quae, id.
                Quam, provident error. Dicta eligendi itaque nobis voluptatum provident accusamus tempora. Sequi ab accusantium non qui, itaque fugiat quaerat atque explicabo quis in iure laborum obcaecati dolores! Cumque, quasi dignissimos!
                In minus reprehenderit perferendis ratione eligendi quae vitae perspiciatis accusantium nam quia modi placeat enim ipsam illum aliquid tempora molestiae atque quis molestias nostrum recusandae accusamus, nobis earum consequatur. Eligendi!
                Laboriosam adipisci fugit, quo cupiditate iusto aspernatur voluptatum officia commodi expedita repellat labore quisquam sit recusandae alias aperiam, quia quasi, quidem similique aliquid at dolores placeat hic repellendus. Error, sequi?
                Dolorem iure similique iste sunt doloremque debitis quod saepe quidem perferendis sit! Non inventore reiciendis quibusdam quos soluta hic, amet dicta repellendus iure, placeat, molestiae vitae qui id quasi autem!
                Neque quae illum laborum animi nesciunt id, dolorum tempore iure laboriosam tempora dolorem corrupti dolore dignissimos asperiores similique, eveniet eligendi ex laudantium! Natus quos dicta, impedit eum libero perspiciatis fuga?</p>
        </div>
    )
}
