import React from 'react'

export const metadata = {
  title: "Contact Page",
  description: "Generated by create next app",
};

export default function ContactPage() {
    return (
        <div>
            <h1 className='text-3xl text-center py-10 font-bold underline'>Contact Page</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam quod error corrupti facilis incidunt modi mollitia voluptatibus quas aperiam odit alias dolorem rem veniam, itaque, cum molestiae quia deleniti praesentium.
                Iure nihil ipsam fuga, soluta incidunt doloribus dolorum accusantium adipis
            </p>
        </div>
    )
}       
